name: Rust

on:
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: sudo apt install -y mingw-w64
    - name: Add windows target
      run: rustup target add x86_64-pc-windows-gnu
    - name: Build
      run: cargo build --release
    - name: Build
      run: cargo build --target x86_64-pc-windows-gnu --release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          target/release/league-of-clash-cli
          target/x86_64-pc-windows-gnu/release/league-of-clash-cli.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
